### ISSUE TITLE
[BUG] Module does not appear on some machines

### ISSUE THREAD

**Issue by NateHawk85** [Foundry-Workshop/ammo-swapper#2]
**Module Version:** v0.1.2

**Describe the bug**
We noticed that some users are able to view this module. However, I, as a GM, am unable to view the icons in the bottom left even when selecting the token for the character. Additionally, I logged in as a separate character and attempted to add a ranged weapon and ammunition to the character sheet. I hooked up the weapon to the ammunition, equipped the weapon, and even then, no icons appeared near the macro bar.

However, one player managed to see it without issues. They initially logged in via Firefox. I can now log in via Chrome into their player account and see the module.

**To Reproduce**
1. Unfortunately, I don't know the steps to recreate this error. It's unknown what causes this. The module shows for some characters and it doesn't for others.

**Expected behavior**
We expected that anyone logged in with a bow (or other weapon consuming ammunition) equipped would be able to see the options to quickly change ammo. This includes the GM.

**Screenshots**
![image](https://user-images.githubusercontent.com/7596412/92553557-ccfd7e00-f228-11ea-902f-f274539c0eab.png)
![image](https://user-images.githubusercontent.com/7596412/92553812-907e5200-f229-11ea-858d-a4abe39e2b9b.png)

**Browser:**
 - Both the native app and Google Chrome. The only player who was successfully able to view it initially started on Firefox.

**Foundry Version:**
0.6.6

**Game System:** 
D&D5E

**Additional context**
None. The same bug exists even when disabling all other modules.

**Comment by JJBocanegra** [comment]
I even tried in a new world with just this module and still doesn't work, also no errors in console.

**Comment by davidR1974** [comment]
Tested and worked for me under certain conditions (Foundry VTT 0.7.9) 
1) GM does not see the ammoSwapper. Only players do.
2) the ranged weapon has to be 1) equipped and 2) set up as an Ammo Consuming (Resource Consumption = Ammunition). The default bow drag and dropped from Items SRD is not configured like that by default.

Hope that helps
