### ISSUE TITLE
Make the bar draggable or otherwise movable to other areas of the screen

### ISSUE THREAD

**Issue by GambetTV** [Foundry-Workshop/ammo-swapper#4]
Right now the bar seems to default to the right of the hotbar, but there are lots of modules that utilize this same area, causing it to block them. Would be nice if we could have some kind of configuration to move this bar elsewhere, especially as it doesn't stay a standard size, but grows as the character has more ranged weapons.

**Comment by Forien** [comment]
Done in [v0.2.0](https://github.com/Foundry-Workshop/ammo-swapper/releases/tag/v0.2.0)
