### ISSUE TITLE
Display charges for weapons that have it

### ISSUE THREAD

**Issue by maplealmond** [Foundry-Workshop/ammo-swapper#6]
When using a repeating crossbow in pf2e or other common magazines, there will be individual non-stacked weapons defined by charges instead of total numbers.  It would be nice to see Repeating Hand Crossbow Magazine (3/5) instead of Repeating Hand Crossbow Magazine (1)

**Comment by Forien** [comment]
I have 0 knowledge of the system, so I had no idea thing like this exists. I will look at this and try to support it
