### ISSUE TITLE
HUD not showing up

### ISSUE THREAD

**Issue by Jadowo** [Foundry-Workshop/ammo-swapper#9]
**Module Version:** v0.3.0

**Describe the bug**
AmmoSwapper HUD is not displaying. Console says it is displaying

**To Reproduce**
1. Follow activation steps
2. Click on character with range weapon equipped
3. HUD doesn't show up
4. Console shows no error

**Expected behavior**
HUD should show up

**Screenshots**
![image](https://github.com/Foundry-Workshop/ammo-swapper/assets/33840143/39653e7d-b419-4485-8a2f-bef6567b106f)

**Browser:**
 - Client

**Foundry Version:** 
11.315

**Game System:** 
DND 3.0.3

**Additional context**
I disabled all other modules except for TokenActionHUD before testing

**Comment by RavenknightDM** [comment]
Seems like D&D 3.0+ broke this mod.

**Comment by Forien** [comment]
@RavenknightDM @Jadowo 

Fixed in [v0.3.1](https://github.com/Foundry-Workshop/ammo-swapper/releases/tag/v0.3.1), sorry for delay :)
